### PR TITLE
Add six package to imports and some pep8 cleanup

### PR DESCRIPTION
**Pull request by A070B24C**
Important change is in phrase_i18n.py

### CODE REVIEW

**Comment by tobstarr** [comment]
Thnak you for you PR, we will look into it soon

**Comment by tobstarr** [comment]
@sacry-dyn could you please have a look?

**Comment by A070B24C** [comment]
Sure @tobstarr, you are welcome.

**Comment by tobstarr** [comment]
@A070B24C sorry for getting back to you that late, thank you for the contribution!

**Pull request merged**
